# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89c35f727ade42f20b43ede36f25c391fa24351de836c0bc8abebcd06193903d8a605651efefa653b7d70278f42bc4e98f50a7ab1e1a6c0dccc9a798f093e895

test:
  secret_key_base: 72d044ee3fcc1fbf47085a81bf595a5ed020651aefe13d7b4cdc525f62cf4933ff3bb883a88c8cd1adb0e49dc77af38b7228e2170fa2338dcd17fc337b5ec253

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
